/**
 * A small, KNOWN fixture dataset (source-shaped, i.e. same shape as jsondata.json rows).
 * Integration tests hand-calculate expected aggregation values from these records, so
 * keep the numbers simple and update the tests if you change them.
 *
 * 8 records. Summary of relevant dimensions:
 *  - topic:   oil x3, gas x1, market x2, gdp x1, tech x1
 *  - sector:  Energy x3, Financial services x1, Government x1, Retail x1, IT x1  (+1 blank? no)
 *  - region:  World x4, Northern America x2, Western Africa x1, Western Asia x1
 *  - country: USA x2, "" x1, India x1, Saudi Arabia x2, Nigeria x1, China x1
 *  - end_year: 2017 x3, 2018 x2, 2020 x2, "" (null) x1
 *  - pestle:  Economic x4, Industries x2, Political x1, Technological x1
 */
export const FIXTURE = [
  {
    topic: 'oil',
    sector: 'Energy',
    region: 'Northern America',
    country: 'United States of America',
    end_year: 2017,
    start_year: 2016,
    intensity: 10,
    likelihood: 3,
    relevance: 2,
    pestle: 'Economic',
    source: 'EIA',
    impact: '',
    insight: 'A',
    url: 'http://a',
    title: 'oil usa 2017',
    added: 'January, 10 2017 01:00:00',
    published: 'January, 05 2017 00:00:00',
  },
  {
    topic: 'oil',
    sector: 'Energy',
    region: 'World',
    country: '',
    end_year: 2017,
    start_year: '',
    intensity: 20,
    likelihood: 4,
    relevance: 4,
    pestle: 'Industries',
    source: 'Reuters',
    impact: '',
    insight: 'B',
    url: 'http://b',
    title: 'oil world 2017',
    added: 'February, 10 2017 01:00:00',
    published: 'February, 05 2017 00:00:00',
  },
  {
    topic: 'gas',
    sector: 'Energy',
    region: 'Northern America',
    country: 'United States of America',
    end_year: 2018,
    start_year: 2017,
    intensity: 6,
    likelihood: 2,
    relevance: 3,
    pestle: 'Economic',
    source: 'EIA',
    impact: '',
    insight: 'C',
    url: 'http://c',
    title: 'gas usa 2018',
    added: 'March, 10 2017 01:00:00',
    published: 'March, 05 2017 00:00:00',
  },
  {
    topic: 'market',
    sector: 'Financial services',
    region: 'World',
    country: 'India',
    end_year: 2018,
    start_year: 2017,
    intensity: 16,
    likelihood: 4,
    relevance: 4,
    pestle: 'Political',
    source: 'Bloomberg',
    impact: '',
    insight: 'D',
    url: 'http://d',
    title: 'market india 2018',
    added: 'April, 10 2017 01:00:00',
    published: 'April, 05 2017 00:00:00',
  },
  {
    topic: 'gdp',
    sector: 'Government',
    region: 'Western Africa',
    country: 'Nigeria',
    end_year: 2017,
    start_year: '',
    intensity: 8,
    likelihood: 3,
    relevance: 2,
    pestle: 'Economic',
    source: 'IMF',
    impact: '',
    insight: 'E',
    url: 'http://e',
    title: 'gdp nigeria 2017',
    added: 'May, 10 2017 01:00:00',
    published: 'May, 05 2017 00:00:00',
  },
  {
    topic: 'oil',
    sector: 'Energy',
    region: 'World',
    country: 'Saudi Arabia',
    end_year: '',
    start_year: '',
    intensity: 12,
    likelihood: 4,
    relevance: 6,
    pestle: 'Industries',
    source: 'OPEC',
    impact: '',
    insight: 'F',
    url: 'http://f',
    title: 'oil saudi',
    added: 'June, 10 2017 01:00:00',
    published: 'June, 05 2017 00:00:00',
  },
  {
    topic: 'market',
    sector: 'Retail',
    region: 'Western Asia',
    country: 'Saudi Arabia',
    end_year: 2020,
    start_year: '',
    intensity: 4,
    likelihood: 2,
    relevance: 2,
    pestle: 'Economic',
    source: 'MRC',
    impact: '',
    insight: 'G',
    url: 'http://g',
    title: 'market saudi 2020',
    added: 'July, 10 2017 01:00:00',
    published: 'July, 05 2017 00:00:00',
  },
  {
    topic: 'tech',
    sector: 'Information Technology',
    region: 'World',
    country: 'China',
    end_year: 2020,
    start_year: 2018,
    intensity: 24,
    likelihood: 4,
    relevance: 6,
    pestle: 'Technological',
    source: 'IDC',
    impact: '',
    insight: 'H',
    url: 'http://h',
    title: 'tech china 2020',
    added: 'August, 10 2017 01:00:00',
    published: 'August, 05 2017 00:00:00',
  },
];

export default FIXTURE;
