import { createPortal } from 'react-dom';

import styles from './Tooltip.module.css';

/**
 * A fixed-position tooltip rendered into <body> (so it is never clipped by chart
 * containers). Content is trusted, chart-generated HTML.
 *
 * @param {object} props
 * @param {{visible:boolean,x:number,y:number,content:string}} props.tooltip
 */
export function Tooltip({ tooltip }) {
  if (!tooltip.visible) return null;
  return createPortal(
    <div
      className={styles.tooltip}
      style={{ left: tooltip.x + 12, top: tooltip.y + 12 }}
      // content is generated by our own charts (no user input), so this is safe
      dangerouslySetInnerHTML={{ __html: tooltip.content }}
    />,
    document.body,
  );
}

export default Tooltip;
